const fs = require('fs');
const path = require('path');

const arPath = path.join(__dirname, 'src', 'lib', 'i18n', 'dictionaries', 'ar.json');
const enPath = path.join(__dirname, 'src', 'lib', 'i18n', 'dictionaries', 'en.json');

const arKeys = {
  "section_title": "🛡️ الأمان والدخول",
  "auth_logs": "سجلات المصادقة",
  "ban_list": "قائمة الحظر",
  "auth_logs_title": "سجلات المصادقة",
  "auth_logs_desc": "مراقبة جميع محاولات تسجيل الدخول والتحقق",
  "search_ip_identifier": "بحث برقم IP أو المعرف...",
  "status_all": "جميع الحالات",
  "status_success": "نجاح",
  "status_failed": "فشل",
  "status_blocked": "محظور",
  "status_rate_limit": "تجاوز الحد",
  "method_all": "جميع الطرق",
  "action_login": "تسجيل دخول",
  "action_register": "تسجيل حساب",
  "action_verify": "تحقق OTP",
  "col_date": "التاريخ",
  "col_action": "الإجراء",
  "col_method": "الطريقة",
  "col_location": "الموقع",
  "col_ip": "IP",
  "col_identifier": "المعرف",
  "col_ip_country": "IP والدولة",
  "col_device": "الجهاز",
  "col_status": "الحالة",
  "no_logs": "لا توجد سجلات",
  "ban_list_title": "قائمة الحظر",
  "ban_list_desc": "إدارة حظر أرقام IP، الأجهزة، والمستخدمين",
  "search_bans": "بحث في قائمة الحظر...",
  "type_all": "جميع الأنواع",
  "type_ip": "IP",
  "type_country": "الدولة",
  "type_device": "الجهاز",
  "type_email": "البريد",
  "type_phone": "الهاتف",
  "add_ban": "إضافة حظر جديد",
  "col_target": "الهدف",
  "col_type": "النوع",
  "col_reason": "السبب",
  "col_expires": "ينتهي في",
  "col_created": "تاريخ الإضافة",
  "col_actions": "الإجراءات",
  "unban": "فك الحظر",
  "edit": "تعديل",
  "add_ban_title": "إنشاء حظر جديد",
  "ban_target": "القيمة للحظر (مثال: 192.168.1.1)",
  "ban_type": "نوع الحظر",
  "ban_reason": "السبب (اختياري)",
  "ban_duration": "المدة",
  "duration_1h": "ساعة واحدة",
  "duration_24h": "24 ساعة",
  "duration_1w": "أسبوع",
  "duration_1m": "شهر",
  "duration_permanent": "دائم",
  "cancel": "إلغاء",
  "save": "حفظ الحظر",
  "success_added": "تمت إضافة الحظر بنجاح",
  "success_removed": "تم فك الحظر بنجاح"
};

const enKeys = {
  "section_title": "🛡️ Security & Access",
  "auth_logs": "Auth Logs",
  "ban_list": "Ban List",
  "auth_logs_title": "Auth Logs",
  "auth_logs_desc": "Monitor all OTP and registration attempts",
  "search_ip_identifier": "Search by IP or Identifier...",
  "status_all": "All Statuses",
  "status_success": "Success",
  "status_failed": "Failed",
  "status_blocked": "Blocked",
  "status_rate_limit": "Rate Limited",
  "method_all": "All Methods",
  "action_login": "Login",
  "action_register": "Register",
  "action_verify": "Verify OTP",
  "col_date": "Date",
  "col_action": "Action",
  "col_method": "Method",
  "col_location": "Location",
  "col_ip": "IP",
  "col_identifier": "Identifier",
  "col_ip_country": "IP & Country",
  "col_device": "Device",
  "col_status": "Status",
  "no_logs": "No logs found",
  "ban_list_title": "Ban List",
  "ban_list_desc": "Manage blocked IPs, devices, and users",
  "search_bans": "Search bans...",
  "type_all": "All Types",
  "type_ip": "IP",
  "type_country": "Country",
  "type_device": "Device",
  "type_email": "Email",
  "type_phone": "Phone",
  "add_ban": "Add New Ban",
  "col_target": "Target",
  "col_type": "Type",
  "col_reason": "Reason",
  "col_expires": "Expires At",
  "col_created": "Created At",
  "col_actions": "Actions",
  "unban": "Unban",
  "edit": "Edit",
  "add_ban_title": "Create New Ban",
  "ban_target": "Value to block (e.g. 192.168.1.1)",
  "ban_type": "Ban Type",
  "ban_reason": "Reason (optional)",
  "ban_duration": "Duration",
  "duration_1h": "1 Hour",
  "duration_24h": "24 Hours",
  "duration_1w": "1 Week",
  "duration_1m": "1 Month",
  "duration_permanent": "Permanent",
  "cancel": "Cancel",
  "save": "Submit Ban",
  "success_added": "Ban added successfully",
  "success_removed": "Ban removed successfully"
};

let ar = JSON.parse(fs.readFileSync(arPath, 'utf8'));
let en = JSON.parse(fs.readFileSync(enPath, 'utf8'));

ar.security = { ...ar.security, ...arKeys };
en.security = { ...en.security, ...enKeys };

fs.writeFileSync(arPath, JSON.stringify(ar, null, 2), 'utf8');
fs.writeFileSync(enPath, JSON.stringify(en, null, 2), 'utf8');

console.log('ar.json and en.json updated.');
